- hosts: master,22Q1
  become: yes
  user: svcacc
  connection: ssh
  gather_facts: yes
  tasks:
  - name: install git
    command: sudo yum install git -y
  - name: install httpd
    command: sudo yum install httpd -y
  - name: start httpd
    action: service name=httpd state=started
- hosts: master
  become: yes
  user: svcacc
  connection: ssh
  gather_facts: yes
  tasks:
  - name: pulling master branch
    command: sudo git clone https://github.com/shubhamg12345/ansible.git -b master
  - name: deployment
    command: mv /home/svcacc/ansible/index.html /var/www/html
- hosts: 22Q1
  become: yes
  user: svcacc
  connection: ssh
  gather_facts: yes
  tasks:
  - name: pulling 22Q1 branch
    command: sudo git clone https://github.com/shubhamg12345/ansible.git -b 22Q1
  - name: deployment
    command: mv /home/svcacc/ansible/index.html /var/www/html
